export { default as Button } from "./Button/Button";
export { default as Footer } from "./Footer/Footer";
export { default as Header } from "./Header/Header";
export { default as Input } from "./Input/Input";
export { default as Select } from "./Select/Select";
export { default as HomeTable } from "./HomeTable/HomeTable";
export { default as CommonPageTable } from "./CommonPageTable/CommonPageTable";
export { default as ManageRPEsTable } from "./ManageRPEsTable/ManageRPEsTable";
export { default as DeleteModal } from "./DeleteModal/DeleteModal";
